version: 2
jobs:
  build:
    docker:
      - image: ubuntu:rolling
    steps:
     - run:
          name: Install tools and dependencies
          command: apt update ; apt install -y build-essential git libmysql++-dev mysql-server libssl-dev zlibc libbz2-dev libboost-dev cmake pgloader postgresql ; apt upgrade -y
     - checkout
     - run:
          name: Configure CMake
          command: mkdir _build ; cd _build ; cmake .. -DDEBUG=1
     - run:
          name: Build with make
          command: make -j$(nproc) install
