version: 2
jobs:
  build:
    docker:
      - image: ubuntu:rolling
    steps:
     - run:
          name: Install tools and dependencies
          command: export DEBIAN_FRONTEND=noninteractive ;  apt update ; apt install -yq build-essential git libmysql++-dev mysql-server libssl-dev zlibc libbz2-dev libboost-all-dev cmake pgloader postgresql ; apt upgrade -yq
     - checkout
     - run:
          name: Configure CMake
          command: mkdir _build ; cd _build ; cmake .. -DDEBUG=1
     - run:
          name: Build with make
          command: cd _build ; make -j$(nproc) install
